- hosts: test
  tasks:
  - name: Install git
    become: true
    apt:
      name: git
      state: latest
      update_cache: true
  - name: Git clone repo
    git:
      repo: https://github.com/Matt25969/SelfReflection
      dest: ~/gitTest
