- hosts: jenkins
  become: true
  tasks:
  - name: jenkins user
    user:
      name: jenkins
      shell: /bin/bash
  - name: install java
    apt:
      name: openjdk-8-jdk
      state: latest
      update_cache: true
  - name: jenkins gpg key
    apt_key:
      url: "https://pkg.jenkins.io/debian/jenkins.io.key"
      state: present
  - name: jenkins apt repo
    apt_repository:
      repo: "deb http://pkg.jenkins.io/debian-stable binary/"
      state: present
  - name: install jenkins
    apt:
      name: jenkins
      state: latest
      update_cache: true
  - name: jenkins service
    service:
      name: jenkins
      state: started
  - name: ssh folder
    file:
      path: /home/jenkins/.ssh
      state: directory
      mode: "0700"
      owner: jenkins
      group: jenkins
  - name: install private key
    copy:
      src: ~/.ssh/ansible_id_rsa
      dest: /home/jenkins/.ssh/id_rsa
      owner: jenkins
      group: jenkins
      mode: "0600"
  - name: display jenkins password
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword

- hosts: docker
  become: true
  tasks:
  - name: prerequisites
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      state: latest
      update_cache: true
  - name: docker gpg key
    apt_key:
      url: "https://download.docker.com/linux/debian/gpg"
      state: present
  - name: docker apt repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
      state: present
  - name: install docker
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
      update_cache: true
  - name: docker service start
    service:
      name: docker
      state: started
  - name: jenkins user
    user:
      name: jenkins
      shell: /bin/bash
      groups: docker
      append: yes

- hosts: swarm-master
  become: true
  tasks:
  - name: ssh folder
    file:
      path: /home/jenkins/.ssh
      state: directory
      mode: "0700"
      owner: jenkins
      group: jenkins
  - name: add public key
    copy:
      src: ~/.ssh/ansible_id_rsa.pub
      dest: /home/jenkins/.ssh/authorized_keys
      owner: jenkins
      group: jenkins
      mode: "0600"

- hosts: jenkins
  become: true
  tasks:
  - name: display jenkins password
    shell: |
            echo "---Jenkins Password---"
            cat /var/lib/jenkins/secrets/initialAdminPassword
